### ISSUE TITLE
Scala test runner fails to evaluate Two Fer

### ISSUE THREAD

**Issue by artamonovkirill** [exercism/scala-test-runner#36]
```
An error occurred while running your tests. This might mean that there was an issue in our infrastructure, or it might mean that you have something in your code that's causing our systems to break.

Please check your code, and if nothing seems to be wrong, try running the tests again.
```

Example solution:
```
object Twofer {
  def twofer(name: String = "you"): String = s"One for $name, one for me."
}
```

All tests pass with `sbt test`

Other exercises seem to be OK.

**Comment by ErikSchierboom** [comment]
The issue is caused by a mismatch between the name of the files that are used in the exercise versus the one the test runner expects. These are the problematic exercises:

```shell
exercises/practice/simple-cipher: SimpleCipher
exercises/practice/binary-search-tree: BinarySearchTree
exercises/practice/kindergarten-garden: KindergartenGarden
exercises/practice/linked-list: LinkedList
exercises/practice/complex-numbers: ComplexNumbers
exercises/practice/two-fer: TwoFer
exercises/practice/parallel-letter-frequency: ParallelLetterFrequency
exercises/practice/largest-series-product: LargestSeriesProduct
exercises/practice/prime-factors: PrimeFactors
exercises/practice/sgf-parsing: SgfParsing
exercises/practice/pangram: Pangram
Probably the best way to fix this is to detect the correct test file name.
```

@jcranky If you'd like, maybe you could look into this?

**Comment by artamonovkirill** [comment]
I was thinking to fix it myself, but couldn't find any mismatches in the code (in both exercism/scala and exercism/scala-test-runner). What am I missing?

**Comment by ErikSchierboom** [comment]
I should probably have explained a bit better, but try running `./bin/run-in-docker.sh simple-cipher /Users/erik/Code/exercism/scala/exercises/practice/simple-cipher  /Users/erik/Code/exercism/scala/exercises/practice/simple-cipher`.
That will output:

```bash
simple-cipher: testing...
^CTraceback (most recent call last):
  File "/opt/test-runner/bin/parse_tests.py", line 176, in <module>
    exit_code = run(*sys.argv[1:])
  File "/opt/test-runner/bin/parse_tests.py", line 129, in run
    with open(test_file_path, encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/solution/simple-cipher-test.el'
jq: invalid JSON text passed to --argjson
Use jq --help for help with command-line options,
```

It tries to find `simpler-cipher-test`, but the file is `CipherTest`.

**Comment by artamonovkirill** [comment]
The extension is also `.el` - is it expecting Lisp?

And where is this `parse_tests.py` coming from?

**Comment by ErikSchierboom** [comment]
No idea. Something really weird is happening. Would you mind running the Scala test runner locally on your machine on a simple-cipher solution?

**Comment by artamonovkirill** [comment]
Running `./bin/run-in-docker.sh two-fer /Users/kirill/workspace/exercism/scala/two-fer /Users/kirill/workspace/exercism/scala/two-fer` locally takes a while (> 2 minutes, possibly due to `WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`) but succeeds in the end.

**Comment by artamonovkirill** [comment]
This is likely the culprit: [exercise=$(echo "${slug}" | sed -E 's/(^|-)([a-z])/\U\2/g')](https://github.com/exercism/scala-test-runner/blob/main/bin/run.sh#L28).
An easy quick fix would be to rename all the test classes for exercises with dashes to cames-cased exercise names (`foo-bar` -> `FooBarTest`).
But it feels weird that the exercise name and not `files.test` from `config.json` is used.

**Comment by ErikSchierboom** [comment]
> But it feels weird that the exercise name and not files.test from config.json is used.

I would be more than happy for this to change, if you're up to it.

> An easy quick fix would be to rename all the test classes for exercises with dashes to cames-cased exercise names (foo-bar -> FooBarTest).

That is also an option. So `CipherTest` should be `SimpleCipherTest`: 
https://github.com/exercism/scala/blob/main/exercises/practice/simple-cipher/src/test/scala/CipherTest.scala

**Comment by artamonovkirill** [comment]
> > But it feels weird that the exercise name and not files.test from config.json is used.
> 
> I would be more than happy for this to change, if you're up to it.

Can I count on `.exercism/config.json` to be there?

**Comment by ErikSchierboom** [comment]
No, you can could on `.meta/config.json` to be present :)

**Comment by artamonovkirill** [comment]
> No, you can could on `.meta/config.json` to be present :)

I just re-downloaded the exercise with CLI, and it's `.exercism`:
```
⋊> ~/w/e/source exercism version                                                                               21:03:43
exercism version 3.1.0
⋊> ~/w/e/source exercism download --exercise=two-fer --track=scala                                             21:03:47

Downloaded to
/Users/kirill/workspace/exercism/scala/two-fer
⋊> ~/w/e/source ls /Users/kirill/workspace/exercism/scala/two-fer/.meta/config.json                            21:03:56
ls: /Users/kirill/workspace/exercism/scala/two-fer/.meta/config.json: No such file or directory
⋊> ~/w/e/source ls /Users/kirill/workspace/exercism/scala/two-fer/.exercism/config.json                        21:04:12
/Users/kirill/workspace/exercism/scala/two-fer/.exercism/config.json
```
🤔

**Comment by ErikSchierboom** [comment]
The test runner isn't using the CLI to download the exercise, but instead uses a different path.

**Comment by artamonovkirill** [comment]
Finalized https://github.com/exercism/scala-test-runner/pull/38
